<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width">';
echo '<title>PixelatedWarrior</title>';
echo '<link href="style.css" rel="stylesheet" type="text/css" />';
echo '<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">';
echo '<link rel="icon" href="pfp.png">';
echo '<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>';
echo '<script src="script.js"></script>';
echo '</head>';
echo '<body>';
echo '';
echo '<div class="container">';
echo '';
echo '<!--────────────────Header───────────────-->';
echo '<header>';
echo '<a class="logo" href="#home">';
echo '<img src="pfp.png" />';
echo '</a>';
echo '<nav>';
echo '<ul class="nav-bar"><div class="bg"></div>';
echo '<li><a class="nav-link active" href="#home">Home</a></li>';
echo '<li><a class="nav-link"  href="#contact">Contact</a></li>';
echo '<li><a class="nav-link" href="mailto:me@pixelatedwarrior1234.tech">Email</a></li>';
echo '<li><a class="nav-link" href="https://stats.uptimerobot.com/vxnWEFE7MY">Status</a></li>';
echo '</ul>';
echo '';
echo '<div class="hamburger">';
echo '<div class="line1"></div>';
echo '<div class="line2"></div>';
echo '<div class="line3"></div>';
echo '</div>';
echo '</nav>';
echo '</header>';
echo '<main>';
echo '<!--─────────────────Home────────────────-->';
echo '<div id="home">';
echo '<div class="filter"></div>';
echo '<section class="intro">';
echo '<h3>PixelatedWarrior<hr></h3>';
echo '<p>Programmer</p>';
echo '<p>Professional Weirdo</p>';
echo '<p>me@pixelatedwarrior1234.tech</p>';
echo '';
echo '<!--────social media links─────-->';
echo '';
echo '<div class="social-media">';
echo '<a href="https://www.youtube.com/channel/UCmO94dFoTRntCKZUwi62lJA?app=desktop" target="_blank"><i class='fab fa-youtube'></i></a>';
echo '<a href="https://discord.gg/ntts" target="_blank"><i class="fab fa-discord"></i></a>';
echo '</div>';
echo '';
echo '</section>';
echo '</div>';
echo '';
echo '';
echo '';
echo '<!--──────────────Contact────────────────-->';
echo '<div id="contact">';
echo '<!--────social media links─────-->';
echo '<h3>Contact.<hr></h3>';
echo '<p>Feel free to contact me on my social media.</p>';
echo '<div class="social-media">';
echo '<a href="https://www.youtube.com/channel/UCmO94dFoTRntCKZUwi62lJA?app=desktop" target="_blank"><i class='fab fa-youtube'></i></a>';
echo '<a href="https://discord.gg/ntts" target="_blank"><i class="fab fa-discord"></i></a>';
echo '</div>';
echo '</div>';
echo '<!--lol keep it lmao-->';
echo '</main>';
echo '<footer class="copyright">© 2021';
echo '<a href="https://repl.it/@PixelatedWarrior" target="_blank"> PixelatedWarrior</a>';
echo '</footer>';
echo '';
echo '</div>';
echo '</body>';
echo '</html>';
echo '';
?>
